Repository afgalvan/Tilia, pull requests merged in 2021-11, with the labels that each got.

#75 chore: medical order layout added
  src/Client/Presentation/Components/Atomic/SidebarUserControl.xaml
  src/Client/Presentation/Components/Atomic/SidebarUserControl.xaml.cs
  src/Client/Presentation/Components/MedicalOrders/MedicalOrderUserControl.xaml
  src/Client/Presentation/Components/MedicalOrders/MedicalOrderUserControl.xaml.cs
Labels: ui

#74 chore: add entities behaviors
  src/Client/Presentation/App.xaml.cs
  src/Server/Domain/Employees/Employee.cs
  src/Server/Domain/MedicalFiles/MedicalAppointment.cs
  src/Server/Domain/Meetings/Meeting.cs
  src/Server/Domain/Patients/Patient.cs
  test/Server.Test/HubConnectionTest.cs
Labels: core, domain

#78 Gui improvements
  src/Client/Presentation/Components/MedicalOrders/MedicalOrderUserControl.xaml
  src/Client/Presentation/Components/Patients/PatientBasicDataRegisterUserControl.xaml
  src/Client/Presentation/Components/Patients/PatientContactDataRegisterUserControl.xaml
  src/Client/Presentation/Components/Patients/PatientMedicalBackgroundUserControl.xaml
  src/Client/Presentation/Components/Patients/PatientMedicalBackgroundUserControl.xaml.cs
  src/Client/Presentation/Components/Patients/PatientMedicalDataRegisterUserControl.xaml
  src/Client/Presentation/Components/Patients/PatientMedicalDataRegisterUserControl.xaml.cs
Labels: core, ui

#79 refactor domain entities
  src/Server/Domain/MedicalFiles/MedicalAppointment.cs
  src/Server/Domain/MedicalFiles/MedicalFile.cs
  src/Server/Domain/MedicalFiles/MedicalNotes/MedicalNote.cs
  src/Server/Domain/MedicalFiles/MedicalNotes/Referral.cs
  src/Server/Domain/MedicalFiles/MedicalOrders/MedicalOrder.cs
  src/Server/Domain/MedicalFiles/MedicalOrders/Referrals.cs
  src/Server/Domain/Patients/Patient.cs
Labels: core, design, domain

#107 fix next button
  src/Client/Presentation/Components/Atomic/Input/DatePickerUserControl.xaml.cs
  src/Client/Presentation/Components/Patients/PatientsRegisterForms/BasicDataRegisterPage.xaml.cs
  src/Client/Presentation/Components/Patients/PatientsRegisterForms/ContactDataRegisterPage.xaml.cs
  src/Client/Presentation/Components/Patients/RegisterPatientUserControl.xaml.cs
  src/Client/Presentation/Extensions/ServiceCollectionExtensions.cs
  src/Server/Application/Users/Authenticate/AuthenticateCommand.cs
  src/Server/Application/Users/Authenticate/AuthenticateCommandHandler.cs
  src/Server/Application/Users/Authenticate/UserAuthenticator.cs
  src/Server/Server/Controllers/AuthenticationController.cs
  src/Server/Server/Controllers/IdTypesController.cs
  src/Server/Server/Controllers/LocationsController.cs
  src/Server/Server/Controllers/RootController.cs
  src/Server/Server/Controllers/UsersController.cs
  src/Server/Server/Extensions/EndpointExtensions.cs
  src/Server/Server/Extensions/ServiceCollectionExtensions.cs
  src/Server/Server/Hubs/UserHub.cs
  src/Shared/Requests/Auth/AuthenticationResponse.cs
  src/Shared/Requests/Auth/LoginUserRequest.cs
Labels: core, ui

#113 http client support
  src/Client/Presentation/Extensions/ServiceCollectionExtensions.cs
  src/Client/Presentation/Services/Http/Connection/RestFetcher.cs
  src/Client/Presentation/Windows/MainWindow.xaml.cs
  src/Shared/Domain/Domain.csproj
Labels: core
